trigger:
  branches:
    include:
      - main

pool:
  name: Default

variables:
  buildConfiguration: 'Release'

stages:
- stage: BuildAndPublish
  displayName: '🔨 Build → Test → Publish'
  jobs:
  - job: BuildJob
    displayName: 'Build & Test Job'
    steps:

      # 1) Checkout your repo
      - checkout: self

      # 2) Make sure the .NET SDK is available
      - task: UseDotNet@2
        displayName: 'Install .NET SDK (7.x)'
        inputs:
          packageType: 'sdk'
          version: '8.0.x'

      # 3) Build your solution (at repo root)
      - script: |
          dotnet build devops-webapp-solution.sln --configuration $(buildConfiguration)
        displayName: 'Build Solution'

      # 4) Run unit tests (point at your Test project folder)
      - script: |
          dotnet test devopswebapp.Tests/devopswebapp.Tests.csproj \
            --configuration $(buildConfiguration) --no-build \
            --logger "trx;LogFileName=test_results.trx"
        displayName: 'Run Unit Tests'

      # 5) Publish your web‑app project to the staging folder
      - script: |
          dotnet publish devopswebapp/devopswebapp.csproj \
            --configuration $(buildConfiguration) \
            --output $(Build.ArtifactStagingDirectory)
        displayName: 'Publish WebApp → Staging'

      # 6) Push everything in the staging folder as a pipeline artifact
      - task: PublishPipelineArtifact@1
        displayName: 'Publish drop Artifact'
        inputs:
          targetPath: '$(Build.ArtifactStagingDirectory)'
          artifact: 'drop'

