itrigger:
  branches: [ main ]

pool:
  name: Default

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Compile
    steps:
    - checkout: self
    - script: dotnet build -c Release
      displayName: 'Build'

    - script: dotnet test -c Release --no-build --logger "trx;LogFileName=test_results.trx"
      displayName: 'Test'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.SourcesDirectory)/bin/Release'
        artifact: drop
